services:
  sb-postgres:
    image: postgres:15-alpine
    container_name: sb-postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - sb-pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 3s
      retries: 5

  scoreboard:
    build:
      context: .
    container_name: scoreboard
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - sb-postgres
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}


  user-worker:
    build:
      context: .
      dockerfile: broker/Dockerfile
    container_name: user-worker
    command: python -m broker.workers.user_worker
    environment:
      - USER_SERVER=${USER_SERVER}
      - NEW_USER_TOPIC=${NEW_USER_TOPIC}
volumes:
  sb-pg: