from os import getenv

# broker
USER_SERVER = getenv("USER_SERVER")
NEW_USER_TOPIC = getenv("NEW_USER_TOPIC")
CURRENCY_CHANGE_TOPIC = getenv("CURRENCY_CHANGE_TOPIC")
USERNAME_CHANGE_TOPIC = getenv("USERNAME_CHANGE_TOPIC")
