from os import getenv

# broker
KAFKA_SERVER = getenv("KAFKA_SERVER")

NEW_USER_TOPIC = getenv("NEW_USER_TOPIC")
CURRENCY_CHANGE_TOPIC = getenv("CURRENCY_CHANGE_TOPIC")
USERNAME_CHANGE_TOPIC = getenv("USERNAME_CHANGE_TOPIC")
