from getopt import GetoptError
from os import getenv

# broker
KAFKA_SERVER = getenv("KAFKA_SERVER")

NEW_USER_TOPIC = getenv("NEW_USER_TOPIC")
CURRENCY_CHANGE_TOPIC = getenv("CURRENCY_CHANGE_TOPIC")
USERNAME_CHANGE_TOPIC = getenv("USERNAME_CHANGE_TOPIC")

CHEST_OPEN_TOPIC = getenv("CHEST_OPEN_TOPIC")

GUILD_CREATE_TOPIC = getenv("GUILD_CREATE_TOPIC")
GUILD_DELETE_TOPIC = getenv("GUILD_DELETE_TOPIC")
GUILD_MEMBER_CHANGE_TOPIC = getenv("GUILD_MEMBER_CHANGE_TOPIC")
GUILD_START_GUILD_WAR_TOPIC = getenv("GUILD_START_GUILD_WAR_TOPIC")

GUILD_WAR_END_TOPIC = getenv("GUILD_WAR_END_TOPIC")

CORE_MATCH_END_TOPIC = getenv("CORE_MATCH_END_TOPIC")